# 实例方法
## Promise.prototype.then()

::: tip 

语法：`then(onFulfilled, onRejected)`

参数：

- onFulfilled *[可选]*
  - 一个在此 Promise 对象被兑现时异步执行的函数。它的返回值将成为 `then()` 返回的 Promise 对象的兑现值。此函数被调用时将传入以下参数：
    - `value`：Promise 对象的兑现值。
  - 如果 `onFulfilled` 不是一个函数，则内部会被替换为一个*恒等*函数（`(x) => x`），它只是简单地将兑现值向前传递。
- onRejected *[可选]*
  - 一个在此 Promise 对象被拒绝时异步执行的函数。它的返回值将成为 `catch()` 返回的 Promise 对象的兑现值。此函数被调用时将传入以下参数：
    - `reason`：Promise 对象被拒绝的原因。
  - 如果 `onRejected` 不是一个函数

返回值：立即返回一个新的 `Promise` 对象，该对象始终处于待定状态

:::

```js
const p1 = new Promise((resolve, reject) => {
  resolve("成功！");
  // 或
  //   reject(new Error("错误!"));
});

p1.then(
  (value) => {
    console.log(">>>value", value); // 成功！
  },
  (reason) => {
    console.error(">>>reason", reason); // 错误！
  }
);
```



## Promise.prototype.catch()

`Promise` 实例的 **`catch()`** 方法用于注册一个在 promise 被拒绝时调用的函数。它会立即返回一个等效的 `Promise`对象，这可以允许你链式调用其他 promise 的方法。此方法是 `Promise.prototype.then(undefined, onRejected)`的一种简写形式。

::: tip

语法：`catch(onRejected)`

参数：

- onRejected
  - 一个在此 Promise 对象被拒绝时异步执行的函数。它的返回值将成为 `catch()` 返回的 Promise 对象的兑现值。此函数被调用时将传入以下参数：
    - `reason`：Promise 对象的拒绝值。

返回值：返回一个新的 `Promise`，无论当前的 promise 状态如何，这个新的 promise 在返回时总是处于待定状态。如果 `onRejected` 方法抛出了一个错误或者返回了一个被拒绝的 promise，那么这个新的 promise 也会被拒绝；否则它最终会被兑现。

:::

```js
const p = new Promise((resolve, reject) => {
  throw new Error('出错了!');
});

p.catch((error) => {
  console.error(error);
});
```



## Promise.prototype.finally()

`Promise` 实例的 **`finally()`** 方法用于注册一个在 promise 敲定（兑现或拒绝）时调用的函数。它会立即返回一个等效的 `Promise` 对象，这可以允许你链式调用其他 promise 方法。

这可以让你避免在 promise 的 `then()` 和 `catch()` 处理器中重复编写代码。

::: tip

语法：`finally(onFinally)`

参数：

- onFinally
  - 一个当 promise 敲定时异步执行的函数。它的返回值将被忽略，除非返回一个被拒绝的 promise。调用该函数时不带任何参数。

返回值：返回等效的 `Promise`。如果处理程序抛出错误或返回被拒绝的 promise，那么 `finally()` 返回的 promise 将以该值被拒绝。否则，处理程序的返回值不会影响原始 promise 的状态。

:::